library/statistics.rst:267: [timeout] https://www.itm-conferences.org/articles/itmconf/pdf/2018/08/itmconf_sam2018_00037.pdf: HTTPSConnectionPool(host='www.itm-conferences.org', port=443): Max retries exceeded with url: /articles/itmconf/pdf/2018/08/itmconf_sam2018_00037.pdf (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe970826870>, 'Connection to www.itm-conferences.org timed out. (connect timeout=30)'))
library/tkinter.rst:41: [timeout] https://tkdocs.com/: HTTPSConnectionPool(host='tkdocs.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe96f104470>, 'Connection to tkdocs.com timed out. (connect timeout=30)'))
